# Generated by Django 3.0.14 on 2023-09-25 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense_amount', models.IntegerField()),
                ('expense_type', models.CharField(max_length=30)),
                ('expense_date', models.DateField()),
                ('expense_description', models.TextField(max_length=30)),
            ],
        ),
    ]
