# Generated by Django 3.0.14 on 2023-09-25 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='expensemodel',
            table='expense',
        ),
    ]
