# Generated by Django 3.0.14 on 2023-09-25 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('income', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='incomemodel',
            table='income',
        ),
    ]
